version: '3'
services:
  emby-merge-versions:
    container_name: emby-merge-versions
    image: ghcr.io/fahmula/emby-merge-versions:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - EMBY_BASE_URL=${EMBY_BASE_URL}
      - EMBY_API_KEY=${EMBY_API_KEY}
      - IGNORE_LIBRARY=${IGNORE_LIBRARY}
    env_file:
      - .env