version: '3'
services:
  emby-merge-versions:
    container_name: emby-merge-versions
    image: ghcr.io/fahmula/emby-merge-versions:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - EMBY_BASE_URL=http://192.168.1.5:8096
      - EMBY_API_KEY=123456789
      - IGNORE_LIBRARY=trending
      - MERGE_ON_START=no
    volumes:
      - /mnt/cache/appdata/merge-versions/logs:/app/logs

